def generate_visual(L, W, name, locked=True):
    # Professional Blueprint Color Palette
    colors = {
        'zone0': '#2C3E50', 'zone1': '#27AE60', 'zone2': '#2ECC71', 
        'zone3': '#F1C40F', 'zone4': '#95A5A6', 'pond': '#3498DB', 'text': '#2C3E50'
    }
    
    fig, ax = plt.subplots(figsize=(14, 16), facecolor='white')
    ax.set_xlim(-20, L + 60)
    ax.set_ylim(-60, W + 40)
    
    # 1. Plot Boundary with 'Blueprint' Border
    ax.add_patch(patches.Rectangle((0, 0), L, W, fill=True, color='#F8F9FA', edgecolor=colors['text'], lw=3, zorder=1))
    ax.grid(color='#D1D1D1', linestyle='--', linewidth=0.5, alpha=0.5, zorder=0)

    # 2. Zone 0: Residential (With House Icon Logic)
    ax.add_patch(patches.Rectangle((5, W*0.75), L*0.3, W*0.2, facecolor=colors['zone0'], alpha=0.9, zorder=2))
    plt.text(L*0.15, W*0.85, '🏠 ZONE 0\nRESIDENTIAL', color='white', ha='center', va='center', fontweight='bold', fontsize=12)

    # 3. Zone 1: Kitchen Garden (With Hatching)
    ax.add_patch(patches.Rectangle((L*0.35, W*0.75), L*0.6, W*0.2, facecolor=colors['zone1'], alpha=0.3, hatch='xxxx', edgecolor=colors['zone1'], zorder=2))
    plt.text(L*0.65, W*0.85, '🌿 ZONE 1\nKITCHEN GARDEN', color='#1B5E20', ha='center', va='center', fontweight='bold', fontsize=12)

    # 4. Zone 2: Food Forest (With Tree Icons)
    ax.add_patch(patches.Rectangle((5, W*0.35), L*0.95, W*0.35, facecolor=colors['zone2'], alpha=0.2, edgecolor=colors['zone2'], lw=2, zorder=2))
    plt.text(L/2, W*0.52, '🌳 ZONE 2: DIVERSIFIED FOOD FOREST', color='#1B5E20', ha='center', va='center', fontweight='bold', fontsize=14)
    
    # Adding Tree Markers (Dots)
    for x in np.linspace(20, L-20, 10):
        for y in np.linspace(W*0.4, W*0.6, 3):
            ax.add_patch(patches.Circle((x, y), 2, color='#27AE60', alpha=0.6, zorder=3))

    # 5. Zone 3: Pasture & Pond
    ax.add_patch(patches.Rectangle((5, 5), L*0.6, W*0.25, facecolor=colors['zone3'], alpha=0.2, hatch='...', edgecolor='#F39C12', zorder=2))
    plt.text(L*0.3, W*0.15, '🐄 ZONE 3: PASTURE', color='#7E5109', ha='center', va='center', fontweight='bold', fontsize=12)

    # Professional Pond Design
    pond_r = W * 0.12
    ax.add_patch(patches.Circle((L-pond_r-10, pond_r+10), pond_r, facecolor=colors['pond'], alpha=0.7, edgecolor='#2980B9', lw=2, zorder=3))
    plt.text(L-pond_r-10, pond_r+10, '💧 POND', color='#154360', ha='center', va='center', fontweight='bold', fontsize=10)

    # 6. TECHNICAL TITLE BLOCK (The "Pro" Touch)
    # Bottom Info Bar
    ax.add_patch(patches.Rectangle((0, -50), L, 40, facecolor='#2C3E50', zorder=4))
    plt.text(L/2, -25, f"PROJECT: {name.upper()} | SCALE: 1:200 | AREA: {L*W:,} SQFT", color='white', fontsize=12, fontweight='bold', ha='center')
    plt.text(L/2, -42, f"TECHNICAL SITE ANALYSIS - GENERATED BY AI ARCHITECT 2026", color='#BDC3C7', fontsize=9, ha='center')

    # 7. NORTH ARROW & SCALE BAR
    plt.arrow(L+30, W-20, 0, 20, width=2, color='#2C3E50', head_width=6, zorder=5)
    plt.text(L+30, W+5, 'N', fontsize=16, fontweight='bold', color='#2C3E50')
    
    # Scale Bar
    ax.add_patch(patches.Rectangle((5, -10), 50, 3, color='black', zorder=5))
    plt.text(30, -20, 'SCALE: 50 FT', ha='center', fontsize=9, fontweight='bold')

    # Watermark Logic
    if locked:
        plt.text(L/2, W/2, 'PREVIEW MODE\nPAY $10 TO UNLOCK HIGH-RES BLUEPRINT', 
                 fontsize=40, color='gray', alpha=0.2, ha='center', va='center', rotation=30, zorder=10)

    plt.axis('off')
    buf = io.BytesIO()
    plt.savefig(buf, format='png', bbox_inches='tight', dpi=300) # High DPI for quality
    plt.close(fig)
    return buf
